### PR TITLE
Cachecleaner

### PR DESCRIPTION
**Pull request by papylhomme**
Hello octopi !

I have created a small frontend for **paccache**. It's pretty straightforward and self contained, but still I had to fix *unixcommand.cpp* to retrieve the command's output. I assumed it was a bug, but maybe I read the code wrong, you can review this change in the first commit :  https://github.com/papylhomme/octopi/commit/3e7d9ac9dae9cf74eaa522e6ee0f062d2d2510ec

Other changes to the octopi source tree are related to packaging and a new menuitem to launch the tool from the main app.

Here is a screenshot of the sole window of cachecleaner :

cachecleaner

### CODE REVIEW

**Comment by papylhomme** [comment]
More testing done and the fix in *unixcommand.cpp* breaks something in octopi. Here is 2 screenshots of octopi doing the same update.

Before updating unixcommand.cpp
octopi1

With the so-called fix :D
octopi2

I'm going to revert this and keep you updated with a new implementation for cachecleaner

**Comment by manjaro** [comment]
Ah, ok. Well from the code side it looked fine. Maybe ask Arnt why he wrote it that way. When ready we will use your cachecleaner for sure.

**Comment by papylhomme** [comment]
OK, reverted UnixCommand behaviour and updated cachecleaner, now octopi should work as usual (at least it does for me), and cachecleaner works with its own output accumulator.

**Comment by aarnt** [comment]
Hi papylhomme, 
Thank you for your work!

I'd just ask you to not change Octopi menu items because it will mess with our current translations (the "&amp;" marks).

**Comment by papylhomme** [comment]
You're welcome. Its a feature I can use too with my day to day maintenance, the pacman cache can grow awfully quick !

For the translations, I'm not sure I understand. I did not change the existing items, but added a new one using "&Cache cleaner". Is this a concern ?

BTW, CacheCleaner is localized, but only with french at the moment (it's my mother tongue)

**Comment by aarnt** [comment]
Hi papylhomme,
I meant the code you changed in Octopi's mainwindow.ui. The menu item texts you added an "&amp;" string.
Those changes would generate a new english source ".ts" file.

**Comment by papylhomme** [comment]
This time I cherrypicked the change in ui/mainwindow.ui in order to keep the designer to mess with the rest of the file.

Regarding the translations files, I updated with lupdate on my repo, and the issue I can see is the change of location :

```xml
 -        <location filename="Projects/octopi/ui/mainwindow.ui" line="110"/>
+        <location filename="../../ui/mainwindow.ui" line="110"/>
```

With the new location, QTLinguist is able to display the UI while translating, but I'm not sure if it may be a problem for Transifex.

Should I update the TS file and commit with the translation (at least for french) or leave it as is ?

**Comment by manjaro** [comment]
For transifex it shouldn't matter which location you are using for the file. At least no "hardcoded" paths should be used at all.

**Pull request merged**
