### PR TITLE
Update octopi_pl.ts

### PR DESCRIPTION
**Pull request by artww**
Update polish translation

### CODE REVIEW

**Comment by aarnt** [comment]
Hi @artww . Thanks for your contribution, but Octopi is being translated on transifex. Could you add your changes there?
https://app.transifex.com/arnt/octopi/

**Comment by artww** [comment]
I added translations on https://app.transifex.com/arnt/octopi/

I can't translate two items:

"Make Deps" - I don't know what is "Deps"

"Explicitly" - I need to know the context

**Comment by aarnt** [comment]
@artww 

Hi.
"Explicity" and "As a dependency" were not supposed to be translated (sorry, my fault).

And "Make Deps" are the dependencies needed to compile some package (Dep=dependency). This text may appear in Info tab for some packages.

**Comment by ots25** [comment]
Hi @aarnt
Are Transifex translations synchronized automatically or do they have to be synchronized manually?  Because I completed the translation into Arabic today.
Thank you for your efforts.

**Comment by aarnt** [comment]
Hi @ots25 . 
They are manual.
Thank you very much for your help!

**Pull request closed without merging**
